In [2]:
import numpy as np

a= np.random.randn(5)
print(a)

[-0.10219451 -0.73040301  2.00505325  0.04846729 -0.43408748]


In [3]:
print(a.shape)

(5,)


In [5]:
print(a.T)

[-0.10219451 -0.73040301  2.00505325  0.04846729 -0.43408748]


In [6]:
print(np.dot(a,a.T))

4.754951840088589


In [7]:
a= np.random.randn(5,1)
print(a)

[[-0.28410604]
 [ 0.89636291]
 [-0.11604946]
 [-1.57175866]
 [-0.15790898]]


In [8]:
print(a.T)

[[-0.28410604  0.89636291 -0.11604946 -1.57175866 -0.15790898]]


In [9]:
print(np.dot(a,a.T))

[[ 0.08071624 -0.25466212  0.03297035  0.44654613  0.0448629 ]
 [-0.25466212  0.80346647 -0.10402244 -1.40886617 -0.14154376]
 [ 0.03297035 -0.10402244  0.01346748  0.18240175  0.01832525]
 [ 0.44654613 -1.40886617  0.18240175  2.47042528  0.24819481]
 [ 0.0448629  -0.14154376  0.01832525  0.24819481  0.02493525]]
